#========================Local================================
APP_ACTIVITY=com.ba.mobile.LaunchActivity
APP_PACKAGE=com.pcloudy.appiumdemo
PLATFORM_ANDROID=Android
APP_NAME=pCloudyAppiumDemo.apk
BUNDLEID=com.pcloudy.TestmunkDemo
#Runner=Android
Runner=pCloudyAndroid
#Runner=pCloudyIOS
#Runner=Android
server_address=127.0.0.1
port=4723
Application=https://www.facebook.com/
browserLocation=./driver/chromedriver.exe

#========================pCloudy================================
pCloudy_Endpoint=https://private-poc.pcloudy.com
pCloudy_Username=shyam.dheer@crestechsoftware.com
pCloudy_ApiKey=mj2dswjphhw8b254tx8j2kkj
pCloudy_ApplicationName=MCB.apk
pCloudy_DurationInMinutes=30

#=========================Devices Json Name =====================
DEVICES_JSON_FILE_NAME=AndroidDevices.json
#DEVICES_JSON_FILE_NAME=SingleDevice.json



#======================Retry Limit in case test fails=============
Retry_Limit=3

#======================Screenshot For Extent Report===============
#pass- capture screenshots for ll verification points-Pass or Fail
#fail- capture screenshots for failures only
#None- No screenshots captured
ScreenshotForReport=PASS

#========================Report Choice======================
#Extent, Allure
ReportType=Allure





